/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author PC
 */
public class BaseKeToan extends javax.swing.JFrame {

    /**
     * Creates new form BaseKeToan
     */
    public BaseKeToan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        MainContent = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        PTCTM = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        TKKT = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainContent.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1345, Short.MAX_VALUE)
        );
        MainContentLayout.setVerticalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 977, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuBar1.setName(""); // NOI18N

        jMenu1.setText("Nhập số liệu");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu1.setMinimumSize(new java.awt.Dimension(120, 27));

        PTCTM.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PTCTM.setText("A. Lập phiếu thu, chi tiền mặt");
        PTCTM.setActionCommand("");
        PTCTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTCTMActionPerformed(evt);
            }
        });
        jMenu1.add(PTCTM);

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem4.setText("B. Nhập, xuất kho - Nhập liệu khác");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem5.setText("C. Hóa đơn nhiều dòng");
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator1);

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem2.setText("E. Danh mục khách hàng, C.nhân viên");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem6.setText("F. Danh mục hàng hóa, vật liệu");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem7.setText("G. Danh mục kho hàng hóa, vật liệu");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("H. Danh mục ngân hàng");
        jMenu1.add(jMenuItem8);

        TKKT.setText("P. Danh mục tài khoản kế toán");
        TKKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKKTActionPerformed(evt);
            }
        });
        jMenu1.add(TKKT);

        jMenuItem10.setText("D. Danh mục chi phí (Tiểu mục)");
        jMenu1.add(jMenuItem10);
        jMenu1.add(jSeparator2);

        jMenuItem11.setText("L. Xem, điều chỉnh số dư đầu năm");
        jMenu1.add(jMenuItem11);

        jMenuItem12.setText("M. Mở sổ kế toán năm mới");
        jMenu1.add(jMenuItem12);

        jMenuItem13.setText("N. Ghi số dư cuối năm cũ qua năm mới");
        jMenu1.add(jMenuItem13);

        jMenuItem14.setText("S. In phiếu");
        jMenu1.add(jMenuItem14);

        jMenuItem15.setText("X. Dọn dẹp các tập tin dữ liệu");
        jMenu1.add(jMenuItem15);

        jMenuItem16.setText("K. Kết thúc");
        jMenu1.add(jMenuItem16);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Điều Chỉnh, xử lý");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu2.setMaximumSize(new java.awt.Dimension(150, 32767));
        jMenu2.setMinimumSize(new java.awt.Dimension(150, 27));
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Báo cáo, sổ kế toán");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Giúp đỡ");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu4.setMaximumSize(new java.awt.Dimension(80, 32767));
        jMenu4.setMinimumSize(new java.awt.Dimension(80, 27));
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PTCTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTCTMActionPerformed
        // TODO add your handling code here:
        MainContent.removeAll();
        JpnPhieuThuChiTM jpnTCTM = new JpnPhieuThuChiTM();
        jpnTCTM.setSize(MainContent.getSize());
        MainContent.add(jpnTCTM);
        MainContent.revalidate();
        MainContent.repaint();
        pack();
    }//GEN-LAST:event_PTCTMActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        MainContent.removeAll();
        JpnPhieuNhapXuatKho jpnPNXK = new JpnPhieuNhapXuatKho();
        jpnPNXK.setSize(MainContent.getSize());
        MainContent.add(jpnPNXK);
        MainContent.revalidate();
        MainContent.repaint();
        pack();

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void TKKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKKTActionPerformed
        // TODO add your handling code here:
        MainContent.removeAll();
        JpnTaiKhoanKeToan jpnTKKT = new JpnTaiKhoanKeToan();
        jpnTKKT.setSize(MainContent.getSize());
        MainContent.add(jpnTKKT);
        MainContent.revalidate();
        MainContent.repaint();
        pack();
    }//GEN-LAST:event_TKKTActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        MainContent.removeAll();
        JpnDSKhachHang jpnDSKH = new JpnDSKhachHang();
        jpnDSKH.setSize(MainContent.getSize());
        MainContent.add(jpnDSKH);
        MainContent.revalidate();
        MainContent.repaint();
        pack();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseKeToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseKeToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseKeToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseKeToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseKeToan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainContent;
    private javax.swing.JMenuItem PTCTM;
    private javax.swing.JMenuItem TKKT;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
